// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjD2AUUdVqQMl6HVTrx0KoGqvEfDBKbsY',
    appId: '1:110360596366:web:121cfb75e9a335e8ed9edf',
    messagingSenderId: '110360596366',
    projectId: 'class17-c1816',
    authDomain: 'class17-c1816.firebaseapp.com',
    storageBucket: 'class17-c1816.firebasestorage.app',
    measurementId: 'G-HHN14N5WK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRPmUk25bGTC2Fc97j7yNelE84EDGEXGw',
    appId: '1:110360596366:android:422f4cf794451b50ed9edf',
    messagingSenderId: '110360596366',
    projectId: 'class17-c1816',
    storageBucket: 'class17-c1816.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUJy5yuOgW_19yE0N6MZOhgeJ2pFQToU',
    appId: '1:110360596366:ios:1f4f96758e573aa3ed9edf',
    messagingSenderId: '110360596366',
    projectId: 'class17-c1816',
    storageBucket: 'class17-c1816.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaUJy5yuOgW_19yE0N6MZOhgeJ2pFQToU',
    appId: '1:110360596366:ios:1f4f96758e573aa3ed9edf',
    messagingSenderId: '110360596366',
    projectId: 'class17-c1816',
    storageBucket: 'class17-c1816.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjD2AUUdVqQMl6HVTrx0KoGqvEfDBKbsY',
    appId: '1:110360596366:web:520574c24ecb3c73ed9edf',
    messagingSenderId: '110360596366',
    projectId: 'class17-c1816',
    authDomain: 'class17-c1816.firebaseapp.com',
    storageBucket: 'class17-c1816.firebasestorage.app',
    measurementId: 'G-FMPHX45RP6',
  );
}
